include: # A list of extra configuration files to include.
  - local.yaml
  - secrets.yaml
  - plugins.yaml

original_date: yes # Use the original date for the release.
threaded: yes
per_disc_numbering: no # The track numbers are incremented throughout a multi disk release.

parentwork:
  force: no
  auto: yes

############################ Paths ############################

asciify_path: yes # Convert all non-ASCII characters in paths to ASCII equivalents.
clutter: [
    .DS_Store, # Default.
    Thumbs.DB, # Default.
  ]

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: $artist/Singletons/$title
  comp: Compilations/$album%aunique{}/$track $title
  albumtype:soundtrack: Soundtracks/$album%aunique{}/$track $title
########################################################

########################### Paths ############################
  ext:jpg: $albumpath/scans/cover
  ext:png: $albumpath/scans/cover
  ext:pdf: $albumpath/scans/booklet
#######################################################

max_filename_length: 255 # 0 = unlimited.

############################ Import ############################
import:
  write: yes
  move: yes
  resume: yes
  incremental: no
  incremental_skip_later: no
  quiet_fallback: skip
  none_rec_action: ask
  timid: no
  default_action: apply
  detail: no
  autotag: yes
  duplicate_action: ask
  bell: yes
  log: ~/.config/beets/beet.log

importadded:
  preserve_mtimes: no # After importing files, re-set their mtimes to their original value. Default: no.
  preserve_write_mtimes: no # After writing files, re-set their mtimes to their original value. Default: no.


############################ Sources ############################
spotify:
  source_weight: 1.0
  show_failures: true

beatport4:
  source_weight: 0.7
  art: true
  art_overwrite: false

musicbrainz:
  searchlimit: 20
  extra_tags: [catalognum, country, label, media, year]
  external_ids:
    discogs: true
    spotify: true
    bandcamp: true
    beatport: true
    tidal: true


match:
  preferred:
    media: ["Digital Media|File", "Digital Media"]
    countries: ["XW", "US", "GB|UK"]
  strong_rec_thresh: 0.10
  medium_rec_thresh: 0.04

mbcollection:
  auto: yes

mbsubmit:
  format: $track. $title - $artist ($length)
  threshold: medium



############################ Last.fm ############################
lastimport:
  per_page: 500
  retry_limit: 3

types:
  play_count: int
  rating: float
  bpm: float

lastgenre:
  auto: yes
  count: 3
  force: yes
  separator: "; "
  min_weight: 10
  prefer_specific: no
  source: track
  title_case: yes

############################ Lyrics ############################

  #lyrics:
  #auto: yes
  #fallback: ""
  #force: no
  #sources:
  #  - bandcamp
  #  - genius
  #  - lyricwiki
  #  - musixmatch
  #  - google

############################ Images ############################
fetchart:
  auto: yes
  cautious: no
  enforce_ratio: yes
  quality: 100
  minwidth: 1000
  maxwidth: 3000
  sources:
    - filesystem
    - coverart
    - albumart
    - fanarttv
    - "*"
  high_resolution: true
  store_source: yes

embedart:
  auto: yes
  compare_threshold: 50
  ifempty: yes
  maxwidth: 0
  remove_art_file: no

############################ ReplayGain ############################
replaygain:
  auto: yes
  backend: ffmpeg
  overwrite: no
  targetlevel: 89
  per_disc: no

############################ Maintenance ############################

duplicates:
  album: no
  checksum: ffmpeg -i {file} -f crc -
  copy: none
  count: yes
  delete: no
  format: format_item
  full: yes
  keys: [mb_trackid, mb_albumid]
  merge: no
  move: none
  path: no
  strict: no
  tiebreak: {}

scrub:
  auto: yes

zero:
  fields: comments

############################ Convert ############################

convert:
  auto: true
  tmpdir: /home/cupkax/beets-tmp
  formats:
    flac:
      command: ffmpeg -i $source $dest -y
    aiff:
      command: ffmpeg -i $source -write_id3v2 1 $dest -y
  format: flac
  no_convert:
    - format:flac
    - format:mp3
    - format:aac
  delete_originals: true
  copy_album_art: true
  embed: true

############################ Check ############################

check:
  import: yes
  write-check: yes
  write-update: yes
  convert-update: no
  threads: 4

############################ Edit ############################

edit:
  itemfields:
    - albumartist
    - album
    - disc
    - disctotal
    - albumtype
    - comp
    - year
    - label
    - catalognum
    - cover_art_url
    - artist
    - track
    - tracktotal
    - title
    - genre
    - rating
    - bpm
    - key
    - comments
    - lyrics
  albumfields:
    - albumartist
    - album
    - disctotal
    - albumtype
    - label
    - catalognum
    - cover_art_url
    - comp
    - year
    - genre
    - comments

############################ UI ############################

verbose: no

ui:
  length_diff_thresh: 3
  color: yes
  colors:
    text_success: green
    text_warning: blue
    text_error: red
    text_highlight: blue
    text_highlight_minor: lightgray
    action_default: darkblue
    action: purple
  import:
      indentation:
          match_header: 4
          match_details: 4
          match_tracklist: 7
      layout: newline

hook:
  hooks:
    - event: album_imported
      command: echo "\"{album}\""
    - event: import
      command: echo "imported from {paths}"
    - event: art_set
      command: echo "Coverart saved"
    - event: import_begin
      command: echo "Roon import started..."
    - event: import_task_apply
      command: echo "Metadata applied"
    - event: item_copied
      command: echo "\"{item}\" copied from \"{source}\" to \"{destination}\""
    - event: item_moved
      command: echo "Moved \"{item}\""
    - event: write
      command: echo "Writing to {path}"
    - event: cli_exit
      command: echo "All tasks finished!"