include: # A list of extra configuration files to include.
  # IMPORTANT: Most configurations doesn't seem to work in external files, so leave them here.
  - local.yaml
  - secrets.yaml
  - plugins.yaml

original_date: yes # Use the original date for the release.
threaded: yes
per_disc_numbering: no # The track numbers are incremented throughout a multi disk release.

parentwork:
  force: no
  auto: yes

############################ Paths ############################

asciify_path: yes # Convert all non-ASCII characters in paths to ASCII equivalents.
clutter: [
    .DS_Store, # Default.
    Thumbs.DB, # Default.
  ]

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: $artist/Singletons/$title
  comp: Compilations/$album%aunique{}/$track $title
  albumtype:soundtrack: Soundtracks/$album%aunique{}/$track $title
  ########################################################

  ############################ Paths ############################
  ext:jpg: $albumpath/scans/cover
  ext:png: $albumpath/scans/cover
  ext:pdf: $albumpath/scans/booklet

########################################################

max_filename_length: 255 # 0 = unlimited.

############################ Import ############################
import:
  write: no
  copy: no
  resume: yes
  incremental: no
  incremental_skip_later: no
  quiet_fallback: skip
  none_rec_action: ask
  timid: no
  default_action: apply
  detail: no
  autotag: yes
  duplicate_action: ask
  bell: yes
  log: ~/.config/beets/beet.log

importadded:
  preserve_mtimes: no # After importing files, re-set their mtimes to their original value. Default: no.
  preserve_write_mtimes: no # After writing files, re-set their mtimes to their original value. Default: no.
########################################################

############################ AcousticBrainz ############################
absubmit:
  auto: yes
  force: yes
  pretend: no

chroma:
  auto: yes

acousticbrainz:
  auto: yes
  force: yes
########################################################

############################ MusicBrainz ############################
musicbrainz:
  searchlimit: 20
  extra_tags: [catalognum, country, label, media, year]

match:
  preferred:
    media: ["Digital Media|File", "Digital Media"]
    countries: ["XW", "US", "GB|UK"]
  strong_rec_thresh: 0.75
  medium_rec_thresh: 0.125

mbcollection:
  auto: yes

mbsubmit:
  format: $track. $title - $artist ($length)
  threshold: medium
########################################################

############################ Beetcamp ############################
bandcamp:
  preferred_media: Digital
  include_digital_only_tracks: true
  search_max: 10
  art: true
########################################################

############################ Last.fm ############################
lastimport:
  per_page: 500
  retry_limit: 3
types:
  play_count: int
  rating: float
lastgenre:
  auto: yes
  count: 1
  separator: "; "
  min_weight: 10
  prefer_specific: no
  source: track
  title_case: yes
########################################################

############################ Lyrics ############################

lyrics:
  auto: yes
  fallback: ""
  force: no
  sources:
    - bandcamp
    - genius
    - lyricwiki
    - google
    - musixmatch
########################################################

############################ Images ############################
fetchart:
  auto: yes
  cautious: no
  enforce_ratio: yes
  minwidth: 1000
  maxwidth: 3000
  sources:
    - filesystem
    - coverart
    - albumart
    - fanarttv
    - bandcamp

  store_source: yes
embedart:
  auto: no
  compare_threshold: 50
  ifempty: yes
  maxwidth: 0
  remove_art_file: no
########################################################

############################ ReplayGain ############################
replaygain:
  auto: yes
  backend: ffmpeg
  overwrite: no
  targetlevel: 89
  per_disc: no
########################################################

############################ Maintenance ############################
duplicates:
  album: no
  checksum: ffmpeg -i {file} -f crc -
  copy: none
  count: yes
  delete: no
  format: format_item
  full: yes
  keys: [mb_trackid, mb_albumid]
  merge: no
  move: none
  path: no
  strict: no
  tiebreak: {}
#check:
#  import: yes
#  write-check: yes
#  write-update: yes
#  convert-update: no
#  threads: 1
scrub:
  auto: yes
zero:
  fields: comments
########################################################

############################ UI ############################

verbose: no

ui:
  color: yes
  colors:
    text_success: green
    text_warning: blue
    text_error: red
    text_highlight: blue
    text_highlight_minor: lightgray
    action_default: darkblue
    action: purple

hook:
  hooks:
    #############################################
    - event: album_imported
      command: echo "\"{album}\""
    - event: import
      command: echo "imported from {paths}"
    #############################################
    - event: art_set
      command: echo "Coverart saved"
    - event: import_begin
      command: echo "Roon import started..."
    - event: import_task_apply
      command: echo "Metadata applied"
    - event: item_copied
      command: echo "\"{item}\" copied from \"{source}\" to \"{destination}\""
    - event: item_moved
      command: echo "Moved \"{item}\""
    - event: write
      command: echo "Writing to {path}"
    - event: cli_exit
      command: echo "All tasks finished!"
########################################################
